version: '3'
services:
  front:
    image: rand_chat_front
    working_dir: /app/front
    build: front/
    command: poetry run flask run --host=0.0.0.0 --debug
    ports:
      - "5001:5000"
    volumes:
      - ./front:/app/front/
    networks:
      - minha-rede

  back:
    image: rand_chat_back
    working_dir: /app/back
    command: poetry run flask run --host=0.0.0.0 --debug
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app/back/
    networks:
      - minha-rede

  crud:
    image: rand_chat_crud
    working_dir: /app/simple_crud
    command: poetry run flask run --host=0.0.0.0 --debug
    ports:
      - "5002:5000"
    volumes:
      - ./simple_crud:/app/simple_crud/
    networks:
      - minha-rede

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha
      MONGODB_DATABASE: tcc
      MONGODB_QUIET: true
    networks:
      - minha-rede

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha
      ME_CONFIG_MONGODB_URL: mongodb://root:senha@mongo:27017/
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

#volumes:
#  random_chat:
#    driver: local
#    driver_opts:
#      type: none
#      device: /Users/jlgs/PycharmProjects/random_chat/
#      o: bind
#      bind-propagation: shared
